#cloud-config

packages:
  # Base system packages
  - curl
  - wget
  - git
  - vim
  - nano
  - build-essential
  - python3-pip
  - python3-venv
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  
  # AWS integration
  - amazon-cloudwatch-agent
  - amazon-efs-utils
  
  # Security tools
  - fail2ban
  - rkhunter
  - aide
  - lynis
  - unattended-upgrades
  - apparmor
  - auditd
  
  # Development dependencies
  - pkg-config
  - libssl-dev
  - zlib1g-dev
  - jq
  - yq
  - htop
  - ncdu
  - zip
  - unzip
  - tree
  - tmux
  - imagemagick
  - nodejs
  - npm
  - rustc
  - cargo
  - fd-find
  - fzf
  - ripgrep
  - libffi-dev
  - libyaml-dev

write_files:
  - path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    content: |
      {
        "agent": {
          "metrics_collection_interval": 60,
          "run_as_user": "root"
        },
        "metrics": {
          "metrics_collected": {
            "cpu": {
              "measurement": [
                "cpu_usage_idle",
                "cpu_usage_user",
                "cpu_usage_system",
                "cpu_usage_iowait"
              ],
              "resources": ["*"],
              "totalcpu": true
            },
            "disk": {
              "measurement": [
                "used_percent",
                "free",
                "total",
                "inodes_free",
                "inodes_used"
              ],
              "resources": ["/"],
              "drop_device": true
            },
            "mem": {
              "measurement": [
                "mem_used_percent",
                "mem_total",
                "mem_free",
                "mem_cached",
                "mem_available"
              ]
            },
            "net": {
              "resources": ["*"],
              "measurement": [
                "bytes_sent",
                "bytes_recv",
                "packets_sent",
                "packets_recv"
              ]
            }
          },
          "append_dimensions": {
            "InstanceId": "$${aws:InstanceId}"
          }
        },
        "logs": {
          "logs_collected": {
            "files": {
              "collect_list": [
                {
                  "file_path": "/var/log/auth.log",
                  "log_group_name": "/ubuntu-box/auth",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/syslog",
                  "log_group_name": "/ubuntu-box/syslog",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/docker/docker.log",
                  "log_group_name": "/ubuntu-box/docker",
                  "log_stream_name": "{instance_id}"
                }
              ]
            }
          }
        }
      }

  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      MaxAuthTries 3
      ClientAliveInterval 300
      ClientAliveCountMax 2
      LoginGraceTime 30
      AllowAgentForwarding no
      X11Forwarding no
      Protocol 2
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com

  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3

  - path: /etc/audit/rules.d/audit.rules
    content: |
      # Delete all existing rules
      -D
      
      # Set buffer size
      -b 8192
      
      # Monitor unauthorized access attempts
      -w /var/log/auth.log -p wa -k auth_log
      -w /var/log/syslog -p wa -k syslog
      
      # Monitor system configuration changes
      -w /etc/passwd -p wa -k passwd_changes
      -w /etc/group -p wa -k group_changes
      -w /etc/ssh/sshd_config -p wa -k sshd_config
      
      # Monitor binaries
      -w /usr/bin/docker -p x -k docker_exec
      -w /usr/bin/mise -p x -k mise_exec

runcmd:
  # Initial setup and packages
  - mkdir -p /opt/aws/amazon-cloudwatch-agent/etc
  - mkdir -p /home/ubuntu/.local/bin
  - mkdir -p /etc/ssh/sshd_config.d
  - apt-get update
  - apt-get upgrade -y

  # Enable and start essential services
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades
  - systemctl enable auditd
  - systemctl start auditd

  # Install Docker using official script
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker ubuntu
  - systemctl enable docker
  - systemctl start docker

  # Configure CloudWatch agent and other services
  - systemctl enable amazon-cloudwatch-agent
  - systemctl start amazon-cloudwatch-agent
  - augenrules --load
  - systemctl restart auditd
  - systemctl restart ssh
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - aideinit
  - mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db

  # Create management scripts directory
  - mkdir -p /opt/ubuntu-box/scripts
  - chown -R ubuntu:ubuntu /opt/ubuntu-box

  # Setup automatic security updates
  - echo "APT::Periodic::Update-Package-Lists \"1\";" > /etc/apt/apt.conf.d/20auto-upgrades
  - echo "APT::Periodic::Unattended-Upgrade \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades

power_state:
  mode: reboot
  timeout: 30
  condition: True