services:
  weather:
    build: .
    volumes:
      - .:/usr/src/app
      - ${HOME}/.weather_config.yml:/root/.weather_config.yml:ro
    env_file:
      - .env
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    command: bundle exec ruby weather.rb